### ISSUE TITLE
UI for profile page

### ISSUE THREAD

**Issue by n0land0** [n0land0/sniff#3]
User Story Template

### Tasks
- [x] Create Profile component
- [x] Create Form component for meetup requests (date picker, dropdown with dog parks, submit)
- [x] Create dog parks data

### User Story
As a user, I want to click on a dog, so that I can decide whether I want my dog to meet them.

### Acceptance Criteria
Scenario: User is on the findfriends page and sees a dog they want to learn more about.
- Given: Cards have loaded and are populated with data.
- When: User clicks a card
- Then: User sees an overlay with more dog info and meetup request form
