### ISSUE TITLE
Meetup request

### ISSUE THREAD

**Issue by n0land0** [n0land0/sniff#4]
### Tasks
- [x] Create place to store user's meetup appointments data
- [x] Add conditional render to reflect existing meetup appointments on profile pages
- [x] Add button to leave profile (close or back)

### User Story
As a user, I want to request a meetup with another dog/owner, so that my dog can make a friend.

### Acceptance Criteria
Scenario: User wants to submit a meetup request
- Given: User has filled out the meetup form 
- When: User submits 
- Then: User should see confirmation message
