### ISSUE TITLE
Dashboard/landing page

### ISSUE THREAD

**Issue by n0land0** [n0land0/sniff#5]
### Tasks
- [x] Create Navbar component linking to findfriends and home pages - NavLink?
- [x] Create Playdate component to display user's appointments
- [ ] Add cancel option for Playdate
- [ ] Create Preview container

### User Story
As a user, I want to see what playdates I've scheduled, so that I can plan accordingly.

### Acceptance Criteria
Scenario: User arrives at the site
- Given: User has previously scheduled playdates
- When: User arrives at dashboard page
- Then: User sees info on scheduled meetups
