### ISSUE TITLE
Create backend

### ISSUE THREAD

**Issue by n0land0** [n0land0/sniff#6]
User Story Template

### Tasks
- [x] Create backend repo, separate from this one
- [x] Write Express server
- [x] Write GET endpoint for profiles
- [x] Write GET endpoint for single user - use for both current user and displaying profiles
- [x] Write POST endpoints for single user (use for adding appointments)
- [x] Appointments should contain unique id, ids from both users involved
- [x] Complete missing Dashboard functionality that was modularized to backend
