### ISSUE TITLE
Create database

### ISSUE THREAD

**Issue by n0land0** [n0land0/sniff#7]
### Tasks
- [x] Self-teach Postgres & Knex
- [x] Move dummy data to database
- [x] Write code in Express to connect backend to database
- [x] Rewrite endpoints to replace local variables with data structures from Postgres
