### ISSUE TITLE
Cypress testing

### ISSUE THREAD

**Issue by n0land0** [n0land0/sniff#8]
### Tasks
- [x] Land on results page & see cards
- [ ] Click on profile
- [ ] Profile expands
- [ ] Existing appointment or not
- [ ] Make appointment & UI changes
- [ ] No duplicate appointments
- [ ] Leave profile page
- [ ] Using navbar
- [ ] Land on dashboard page and see appointments
- [ ] Cancel appointment
- [ ] Click on Preview card & navigate to profile
